### PR TITLE
Add downloads to the header

### PR DESCRIPTION
**Pull request by cwebberOps**
We have been running a test via optimizely that does this. It has been super successful.

### CODE REVIEW

**Comment by TrevorBramble** [comment]
:shipit:

**Comment by Padgett** [comment]
Groovy :+1:

**Comment by cnunciato** [comment]
There's a helper for this: https://github.com/chef/chef-web-core/blob/master/lib/chef/web/core/url_helpers.rb#L33

**Comment by TrevorBramble** [comment]
@cnunciato Thanks for the tip!

@cwebberOps :+1:

**Pull request merged**
