### PR TITLE
adding anchor tags for easy bookmarking.

### PR DESCRIPTION
**Pull request by jonong1972**

### CODE REVIEW

**Comment by smith** [comment]
You don't need to use `<a name="logo-usage"></a>`. Using `<h2 id="logo-usage">Logo Usage</h2>` will do the same thing.

See http://www.w3.org/TR/html5/obsolete.html#obsolete-but-conforming-features.

**Comment by jonong1972** [comment]
Im old timey like that. :)

**Comment by cnunciato** [comment]
IDs, please. :)

**Comment by cnunciato** [comment]
Rationale is that we're likely going to want to do this elsewhere, so we should use the new standard in order to avoid propagating the outdated one.

**Comment by smith** [comment]
:+1: to add this, though how does one get an actual link? Do you have to open web inspector and copy it? It would be nice if we could make it automatically link sections like GitHub does in Markdown and README files.

**Comment by jonong1972** [comment]
the 'A's have been updated to IDs

**Pull request merged**
