### PR TITLE
Fix a small typo

### PR DESCRIPTION
**Pull request by jcreedcmu**

### CODE REVIEW

**Comment by mmzyk** [comment]
Knowing very little about all of this, I assume making it modal instead of modals then brings in the foundation/components/reveal library?

**Comment by jcreedcmu** [comment]
I too know very little, but I know that when I made this change, I was able to successfully bring up the modal via 
```js
$('#modal').foundation('reveal', 'open');
```
so if you're asking whether the transitive dependencies are correctly wired up, I conjecture yes.

**Comment by jcreedcmu** [comment]
Turns out @mmzyk was talking about the apparent deletion of
```css
@import 'foundation/components/reveal';
```
at the end of `modals.css`, but it was just the addition of a newline to the end of the file, which github was displaying in a counterintuitive way. Removed the newline change.

**Comment by cnunciato** [comment]
:+1:

**Pull request merged**
