### PR TITLE
Added tm and alt logo to chef-logo.ai

### PR DESCRIPTION
**Pull request by Unikitteh**

### CODE REVIEW

**Comment by cnunciato** [comment]
Minor, but figured worth asking in case it was unintentional: Should the TM symbol should be positioned a couple of pixels above the upper edge of the F in CHEF, or lined up with it?

image

**Comment by Unikitteh** [comment]
Thanks for catching that

**Comment by cnunciato** [comment]
Cool, thanks.

Also, what are the situations in which we don't need to display the trademark symbol? Looking around on the web, it seems much of the time, it's left out:

image

image

image

... and such. It'd be good to capture those in the guidelines, then figure out some way to allow and either opt in or out of it, depending on what the default should be (presumably the latter).

**Comment by Unikitteh** [comment]
As of now the rule is that the logo should always have the TM except for in specific marketing collateral situations which would be handled internally or with special permission. The blanket rule is always include TM.

**Comment by smith** [comment]
Merging

**Pull request merged**
