### PR TITLE
Add directories for icon source files

### PR DESCRIPTION
**Pull request by cnunciato**
Illustrator source files and intermediate SVGs for Chef icons can go here.

cc: @jamescott

### CODE REVIEW

**Comment by jamescott** [comment]
+1 ... I will add the source AI files after this is merged.

**Comment by smith** [comment]
We should exclude these (and possibly other) directories from the [gemspec](https://github.com/chef/chef-web-core/blob/master/chef-web-core.gemspec#L14) (see http://guides.rubygems.org/specification-reference/#files) so that people using this as a Gem don't need to install these source files.

There's probably a similar thing you can do for package.json but I'm not sure what that is.

**Comment by cnunciato** [comment]
@smith absolutely, that occurred to me as well -- will do that.

**Comment by cnunciato** [comment]
@smith package.json includes everything in `dist`, which is built by Grunt. I went ahead and added `images/icons/*.svg` (i.e., the processed SVGs) to the list of files that make it into `dist`.

**Pull request merged**
