### PR TITLE
Updates header Community Link

### PR DESCRIPTION
**Pull request by cwebberOps**
As part of CIA-112 we are changing where the community link points. The
goal being to get folks to resources instead of just the supermarket.

### CODE REVIEW

**Comment by Padgett** [comment]
Code looks fine, Travis is failing at not being able to find chef-web-core on rubygems.org

**Comment by cnunciato** [comment]
Im not sure I understand the changes to VERSION and Gemfile.lock. VERSION should be changed with the rake version task (on the master branch -- see the README), and since the change is related to a template only, the bundle should not need to be modified. Can assist y'all with this today, but you should be able to PR with only the template change here.

**Comment by cwebberOps** [comment]
@cnunciato yup. After getting the failures I realized that i was "doing it wrong" and just pushed a commit reverting those changes.

**Comment by cwebberOps** [comment]
@cnunciato can I get a :+1: before I merge?

**Comment by cnunciato** [comment]
:+1:

**Pull request merged**
